#include <catch2/catch_test_macros.hpp>

#define TAGREADER_REGRESSION_TESTS_NO_MAIN
#include "regression_tests.cpp"
#undef TAGREADER_REGRESSION_TESTS_NO_MAIN

#define TAGREADER_TR_AUDIT_CASE(case_id) \
    TEST_CASE("TR-AUDIT-" #case_id, "[regression][TR-AUDIT-" #case_id "]") \
    { \
        REQUIRE(RunTrAudit##case_id()); \
    }

TAGREADER_TR_AUDIT_CASE(001)
TAGREADER_TR_AUDIT_CASE(002)
TAGREADER_TR_AUDIT_CASE(003)
TAGREADER_TR_AUDIT_CASE(004)
TAGREADER_TR_AUDIT_CASE(005)
TAGREADER_TR_AUDIT_CASE(006)
TAGREADER_TR_AUDIT_CASE(007)
TAGREADER_TR_AUDIT_CASE(008)
TAGREADER_TR_AUDIT_CASE(009)
TAGREADER_TR_AUDIT_CASE(010)
TAGREADER_TR_AUDIT_CASE(011)
TAGREADER_TR_AUDIT_CASE(012)
TAGREADER_TR_AUDIT_CASE(013)
TAGREADER_TR_AUDIT_CASE(014)
TAGREADER_TR_AUDIT_CASE(015)
TAGREADER_TR_AUDIT_CASE(016)
TAGREADER_TR_AUDIT_CASE(017)
TAGREADER_TR_AUDIT_CASE(018)
TAGREADER_TR_AUDIT_CASE(019)
TAGREADER_TR_AUDIT_CASE(020)
TAGREADER_TR_AUDIT_CASE(021)
TAGREADER_TR_AUDIT_CASE(022)
TAGREADER_TR_AUDIT_CASE(023)
TAGREADER_TR_AUDIT_CASE(024)
TAGREADER_TR_AUDIT_CASE(025)
TAGREADER_TR_AUDIT_CASE(026)
TAGREADER_TR_AUDIT_CASE(027)
TAGREADER_TR_AUDIT_CASE(028)
TAGREADER_TR_AUDIT_CASE(029)
TAGREADER_TR_AUDIT_CASE(030)
TAGREADER_TR_AUDIT_CASE(031)

#undef TAGREADER_TR_AUDIT_CASE
