#include <catch2/catch_test_macros.hpp>

#define TAGREADER_REGRESSION_TESTS_NO_MAIN
#include "regression_tests.cpp"
#undef TAGREADER_REGRESSION_TESTS_NO_MAIN

#define TAGREADER_TR_AUDIT_CASE(case_id) \
    TEST_CASE("TR-AUDIT-" #case_id, "[regression][TR-AUDIT-" #case_id "]") \
    { \
        REQUIRE(RunTrAudit##case_id()); \
    }

TAGREADER_TR_AUDIT_CASE(032)
TAGREADER_TR_AUDIT_CASE(033)
TAGREADER_TR_AUDIT_CASE(034)
TAGREADER_TR_AUDIT_CASE(035)
TAGREADER_TR_AUDIT_CASE(036)
TAGREADER_TR_AUDIT_CASE(037)
TAGREADER_TR_AUDIT_CASE(038)
TAGREADER_TR_AUDIT_CASE(039)
TAGREADER_TR_AUDIT_CASE(040)
TAGREADER_TR_AUDIT_CASE(041)
TAGREADER_TR_AUDIT_CASE(042)
TAGREADER_TR_AUDIT_CASE(043)
TAGREADER_TR_AUDIT_CASE(044)
TAGREADER_TR_AUDIT_CASE(045)
TAGREADER_TR_AUDIT_CASE(046)
TAGREADER_TR_AUDIT_CASE(047)
TAGREADER_TR_AUDIT_CASE(048)
TAGREADER_TR_AUDIT_CASE(049)
TAGREADER_TR_AUDIT_CASE(050)
TAGREADER_TR_AUDIT_CASE(051)
TAGREADER_TR_AUDIT_CASE(052)
TAGREADER_TR_AUDIT_CASE(053)
TAGREADER_TR_AUDIT_CASE(054)
TAGREADER_TR_AUDIT_CASE(055)
TAGREADER_TR_AUDIT_CASE(056)

#undef TAGREADER_TR_AUDIT_CASE
